# Generated by Django 5.0.7 on 2024-07-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="upload_soil_data_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N", models.FloatField()),
                ("P", models.FloatField()),
                ("K", models.FloatField()),
                ("Temperature", models.FloatField()),
                ("Humidity", models.FloatField()),
                ("Ph", models.FloatField()),
                ("Rainfall", models.FloatField()),
            ],
        ),
    ]
