# Generated by Django 5.0.7 on 2024-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soil", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload_soil_data_class",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
