# Generated by Django 5.0.7 on 2024-07-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soil", "0002_alter_upload_soil_data_class_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload_soil_data_class",
            name="N",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
