# Generated by Django 5.0.7 on 2024-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soil", "0004_alter_upload_soil_data_class_n"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload_soil_data_class",
            name="predicted_crop",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
